### ISSUE TITLE
Enable travis CI

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-wsdl2rest#12]
Looks like I don't have permissions to enable travis on this repo -https://travis-ci.org/camel-tooling/vscode-wsdl2rest

@apupier or @lhein ?

**Comment by lhein** [comment]
yeah, I lack rights both on github and also on travis.

**Comment by apupier** [comment]
I added you admin rights.
Strange that Brian didn't have it as he created the repository. I need to change a configuration in the Organization for future repo creation (when i will find why...)

**Comment by bfitzpat** [comment]
It may have been something in the way I moved the repo from my personal one to camel-tools. I'm not sure. I didn't create it from scratch. I used "Transfer Ownership" in the repo settings

![image](https://user-images.githubusercontent.com/530878/53172926-c0142d80-35a3-11e9-922a-f1e34169bd6e.png)

**Comment by bfitzpat** [comment]
Just updated the deploy task here - https://github.com/camel-tooling/vscode-wsdl2rest/pull/20

**Comment by bfitzpat** [comment]
Not sure what this means, but suspect that maybe the token isn't around? Ideas? @lhein ? @apupier  ?

```Deploying application
Script failed with status 127
failed to deploy
```

**Comment by apupier** [comment]
> Not sure what this means, but suspect that maybe the token isn't around?

Not sure about the exact meaning but as the VS Code token is nto available, it seems to be an high probability that it is the case. The token needs to be passed as TRAVIS environment variables.

from https://travis-ci.org/camel-tooling/vscode-wsdl2rest 
More Options -> Settings
![image](https://user-images.githubusercontent.com/1105127/53355267-f0075c00-3928-11e9-9dee-bdcea4a0e637.png)

the environment variable needs to be called VSCODE_TOKEN https://github.com/camel-tooling/vscode-wsdl2rest/blob/master/.travis.yml#L27

The token can be retrieved as explained here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token (it is the same than what you did for vscode-yeoman)

**Comment by bfitzpat** [comment]
Ok. Token generated. Token stashed in Travis. Still getting error 127 - https://travis-ci.org/camel-tooling/vscode-wsdl2rest/builds/498262396

**Comment by apupier** [comment]
just noticed that the vsix is not built.
the step "vsce package" is missing https://github.com/camel-tooling/camel-lsp-client-vscode/blob/8b8b1f912bd07d3e4987c60b6df0958015e930ce/.travis.yml#L15 . it requires to install vsce globally https://github.com/camel-tooling/camel-lsp-client-vscode/blob/8b8b1f912bd07d3e4987c60b6df0958015e930ce/.travis.yml#L14

**Comment by bfitzpat** [comment]
Ok, so the token is there and I'm getting 
```
Publishing camel-tooling.vscode-wsdl2rest@0.0.3...
 ERROR  Failed Request: Unauthorized(401) - https://marketplace.visualstudio.com/_apis/gallery
 ERROR  Be sure to use a Personal Access Token which has access to **all accessible accounts**.
See https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions for more information.
Script failed with status 1
```
https://travis-ci.org/camel-tooling/vscode-wsdl2rest/builds/498361725

**Comment by bfitzpat** [comment]
looks like I also need to get a sonar key for the project...
```
ERROR: Error during SonarQube Scanner execution
ERROR: You must define the following mandatory properties for 'Unknown': sonar.projectKey
```
https://travis-ci.org/camel-tooling/vscode-wsdl2rest/builds/498367743

**Comment by apupier** [comment]
> looks like I also need to get a sonar key for the project...

yes, it is due to this configuration: https://github.com/camel-tooling/vscode-wsdl2rest/blob/4cda22a6d6a9bd0f433798f3c05a86a9ef8e8ce4/.travis.yml#L36-L40

**Comment by apupier** [comment]
> Ok, so the token is there and I'm getting
> 
> ```
> Publishing camel-tooling.vscode-wsdl2rest@0.0.3...
>  ERROR  Failed Request: Unauthorized(401) - https://marketplace.visualstudio.com/_apis/gallery
>  ERROR  Be sure to use a Personal Access Token which has access to **all accessible accounts**.
> See https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions for more information.
> Script failed with status 1
> ```

I think it is because the token doesn't have all the correct rights. It seems to mention that the organization selected was not the "All accessible organizations: https://code.visualstudio.com/assets/api/working-with-extensions/publishing-extension/token3.png

**Comment by apupier** [comment]
I created a new Token and updated it in travis settings.
Then I re-triggered a build of the 0.0.3 tag build https://travis-ci.org/camel-tooling/vscode-wsdl2rest/builds/498361725
The extension has been published successfully:
https://marketplace.visualstudio.com/items?itemName=camel-tooling.vscode-wsdl2rest

**Comment by bfitzpat** [comment]
@apupier Can we close this one as done?

**Comment by apupier** [comment]
> @apupier Can we close this one as done?

I think yes :-)
- build green
- can publish a version 
- there is a sonar analysis https://sonarcloud.io/dashboard?id=vscode-wsdl2rest
