### ISSUE TITLE
Fix failing tests looking for project files in wrong directory

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-wsdl2rest#125]
While reviewing https://github.com/camel-tooling/vscode-wsdl2rest/pull/122, discovered that four tests are failing consistently.

**Comment by bfitzpat** [comment]
Issue turned out the tests were looking for the wsdl2rest-generated files in the wrong directory.

**Comment by bfitzpat** [comment]
Created https://github.com/camel-tooling/vscode-wsdl2rest/pull/126

**Comment by bfitzpat** [comment]
Fixed and resolved

**Comment by apupier** [comment]
adding the issue to QA column so that QA team can have a look at it:

![Screenshot from 2019-11-08 17-50-54](https://user-images.githubusercontent.com/1105127/68495379-59799180-0250-11ea-88b1-884545256c12.png)

**Comment by djelinek** [comment]
verified with master branch
