### ISSUE TITLE
Improve release process to include sources when publishing vsix

### ISSUE THREAD

**Issue by nickboldt** [camel-tooling/vscode-wsdl2rest#142]
If https://download.jboss.org/jbosstools/adapters/stable/vscode-wsdl2rest/vscode-wsdl2rest-0.0.10-44.vsix is the latest stable release, then it should also include a source tarball in that folder, so that downstream consumers who have this requirement (eg., Che and CodeReady Workspaces) can easily see the sources for the binary distribution.

OR... if you publish to GH under /releases/ you will get a tarball for free. You used to do this up to 0.0.8 but stopped for some reason.

https://github.com/camel-tooling/vscode-wsdl2rest/releases/tag/0.0.8
https://github.com/camel-tooling/vscode-wsdl2rest/releases/download/0.0.8/vscode-wsdl2rest-0.0.8.vsix
https://github.com/camel-tooling/vscode-wsdl2rest/archive/0.0.8.tar.gz

Now, the latest tag/release 0.0.10 only includes sources but for a different version than the latest vsix file.

https://github.com/camel-tooling/vscode-wsdl2rest/releases/tag/0.0.10
and
https://download.jboss.org/jbosstools/adapters/stable/vscode-wsdl2rest/vscode-wsdl2rest-0.0.10-44.vsix

Some existing examples of where it's done more cleanly/consistently, with source and binary in the same place w/ the same version:

https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/
https://github.com/redhat-developer/omnisharp-theia-plugin/releases/
https://github.com/redhat-developer/vscode-openshift-tools/releases/

**Comment by nickboldt** [comment]
Reasons for this requirement can be seen in [CRW-441](https://issues.redhat.com/browse/CRW-441) and [CRW-491](https://issues.redhat.com/browse/CRW-491) and https://github.com/eclipse/che/issues/14573

cc: @mkuznyetsov

**Comment by apupier** [comment]
> but stopped for some reason.

to follow the practice that the Developer Tooling suggested us to have to use redhat publisher on VS Code Marketplace :-D

> Some existing examples of where it's done more cleanly/consistently, with source and binary in the same place w/ the same version:

I looked to the several pipelines part of the 3 projects you pointed but not found anything related to the push of the vsix/tag/source on github.
Can you point the exact place please? or is it currently a manual process? in this case, I will kindly ask the Developer Tooling team to provide an automated example based on JenkinsFile as we are forced to use it for building the tags :-)

**Comment by apupier** [comment]
I think it is better to continue conversation here https://issues.redhat.com/browse/FUSETOOLS2-80?focusedCommentId=13822639&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13822639 as it is affecting several extensions

**Comment by apupier** [comment]
was covered by https://github.com/camel-tooling/vscode-wsdl2rest/pull/157
