### ISSUE TITLE
Provide icon to the extension

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-wsdl2rest#29]
currently no icon:
![image](https://user-images.githubusercontent.com/1105127/53396441-b96f2700-39a4-11e9-82ae-5c19d3730f60.png)

use the Camel Tooling icon as i tit in Camel Tooling organization? or use a wsdl icon?

**Comment by bfitzpat** [comment]
Using the camel icon for now - created https://github.com/camel-tooling/vscode-wsdl2rest/pull/32
