### ISSUE TITLE
Clicking outside of the VSCode window is going to next Inputbox of the command

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-wsdl2rest#35]
- launch a wsdl 2 rest command
- imagine you want to go copy-paste an URL from elsewhere, then click outside of VS Code
--> the inputbox is validated and it is going to the next one

**Comment by bfitzpat** [comment]
Yes, I noticed that. If I have the URL I want to copy-paste already in the clipboard, it works fine to paste it into the input box, but focus shifts seem to mess it up. 

I'll see what I can do about that, as it doesn't handle Escaping out of it either if you want to simply cancel out of the extension.

**Comment by bfitzpat** [comment]
Fixed the focus issues https://github.com/camel-tooling/vscode-wsdl2rest/pull/38
