### ISSUE TITLE
Update wsdl2rest build to final Fuse 7.3 artifacts when available

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-wsdl2rest#49]
When Fuse 7.3 releases, we will need to update the wsdl2rest version (https://github.com/camel-tooling/vscode-wsdl2rest/blob/453c935e7ace08fd21f0b2fd2292cfa12854bfbb/wsdl2rest/pom.xml#L13) to the final version of those artifacts.

**Comment by bfitzpat** [comment]
Completed

**Comment by apupier** [comment]
in camel-tooling projects, Engineering need to move the issues to "On QA" in "Work planning board"

**Comment by tsedmik** [comment]
verified with master branch
